library(shiny)
library(shiny.grid)
library(shiny.blank)
library(htmltools)
library(tidyr)
library(leaflet)
library(R6)
library(googlesheets)
library(glue)
library(utils)
library(dplyr)
library(jsonlite)
library(modules)

swipeCards <- use("components/swipe-cards.R")

gameManager <- use("logic/gameManager.R")$gameManager$new()
